version: "3"
services:
  django:
    command:
    - "python"
    - "-u"
    - "/opt/.pycharm_helpers/pycharm/django_test_manage.py"
    - "test"
    - "--noinput"
    - "--parallel"
    - "8"
    - "--exclude-tag=integration"
    - "/opt/project"
    environment:
      PYTHONPATH: "/opt/project:/opt/.pycharm_helpers/pycharm_matplotlib_backend:/opt/.pycharm_helpers/pycharm_display:/opt/.pycharm_helpers/pycharm"
      DJANGO_SETTINGS_MODULE: "config.settings.test"
      PYCHARM_DJANGO_MANAGE_MODULE: "manage"
      PYTHONUNBUFFERED: "1"
      PYTHONIOENCODING: "UTF-8"
      PYCHARM_HOSTED: "1"
      PYCHARM_DISPLAY_PORT: "63342"
      PYCHARM_HELPERS_DIR: "/opt/pycharm-professional/plugins/python/helpers/pycharm"
      PYTHONDONTWRITEBYTECODE: "1"
    stdin_open: true
    volumes:
    - "/home/embercraze/gigapay_dev/gigapay:/opt/project:rw"
    - "pycharm_helpers_PY-232.9559.58:/opt/.pycharm_helpers"
    working_dir: "/opt/project"
volumes:
  pycharm_helpers_PY-232.9559.58: {}
